[profile.default]
libs = ["node_modules", "lib"]
out = "artifacts"
src = "contracts"
test = "test"

bytecode_hash = "none"
# evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.19"
# via-ir = true

[fmt]
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
